### ISSUE TITLE
Has anyone been working on this project or is it over

### ISSUE THREAD

**Issue by paul010702** [Nebuleon/ReGBA#13]
The last time it was updated was on 2013 and im beginning to think everyone abandoned tempgba. Maybe im wrong and people are working on it. I would really like to see tempgba succeed and become the best gba emulator for the ds and 3ds.

**Comment by pcercuei** [comment]
Last commit was 15 days ago.
So yes, people are still working on it.

**Comment by Nebuleon** [comment]
I have been testing the performance and reliability of an entirely new [communication protocol and library](https://github.com/Nebuleon/Supercard-API), made specifically to side-step many issues that plague the latest published version of TempGBA on the Supercard DSTwo. I had stopped writing any code for the Supercard after 2013, partly because of unfixable issues with the [official DS2SDK](http://eng.supercard.sc/manual/dstwo/ds2sdk.htm) that were exposed by TempGBA and CATSFC and frustrated me to no end at the time:

* delays of up to 3 seconds to react to button presses or releases from the Nintendo DS;
* incorrect timing of audio submission that led to crackling or half-seconds of missing audio, video or both at unpredictable times;
* the link between the Supercard and DS freezing indefinitely if TempGBA frameskipping is set to 0, depending on the computational demands of a specific game;
* the link between the Supercard and DS freezing indefinitely after a request to turn the backlights on or off unless there's a 50-millisecond delay after the request;
* the double-buffered video update mode showing screen tearing, while the whole point of double-buffering is to avoid screen tearing;

... and partly because, well, I had no Supercard. My development Supercard had stopped being recognised altogether by my Nintendo DS due to the contacts having eroded and it became rather difficult to develop for it, as you might expect.

Now, I'm a bit puzzled by "I would really like to see tempgba succeed":

* Implied by that sentence is "but right now it doesn't". How is it currently not succeeding, i.e. how do you measure success, and where is TempGBA failing? That would be a nice starting point for bug reports.

* Is there any way you could concretely contribute to making this wish come true? Testing of beta versions and bug reporting? Development? Documentation? Money?

Related to that, there's a TempGBA4PSP source code archive floating around, with over 10,000 lines of code changed, and some users are saying that it improved compatibility and accuracy over the code in this repository, but when I looked at it, so much of the changed lines were PSP-specific that I gave up looking for the non-PSP-specific code that implemented the accuracy improvements that could be put in ReGBA's mips directory which is shared by the Supercard DSTwo, PSP and GCW Zero. Perhaps if you speak Japanese, or know someone who does, you could ask the Japanese person to give a short explanation of what they did, and in which files, and that would help me get those changes into ReGBA.

TempGBA4PSP was discussed on GBATemp here: https://gbatemp.net/threads/tempgba4psp.361298/

**Comment by paul010702** [comment]
Would you ever consider getting back into coding for the tempgba? If you are not considering going back into tempgba are you working on a new project that is a gba emulator for the ds/3ds. Btw, thank you for responding.
________________________________

**Comment by Nebuleon** [comment]
For the Nintendo 3DS, in 3DS mode, there's always [mGBA, also known as medusa](https://mgba.io/). It has a Patreon you can contribute to financially if you know which features you want out of a GBA emulator, can convey them to the developers, and wish to accelerate their development.

"Would you ever consider getting back into coding for TempGBA?" Coding what, and for what purpose?

**Comment by paul010702** [comment]
like trying to fix the issues you ran into.

**Comment by Nebuleon** [comment]
Yes.
